#!/usr/bin/env ruby
# the above shebang lets the file know it's a ruby file
#
# puts <<EOS
#       July 2017
# Su Mo Tu We Th Fr Sa
#                    1
#  2  3  4  5  6  7  8
#  9 10 11 12 13 14 15
# 16 17 18 19 20 21 22
# 23 24 25 26 27 28 29
# 30 31
# EOS

require_relative 'lib/month'

month = ARGV[0].to_i
year = ARGV[1].to_i

month = Month.new(month,year)
puts month.to_s
