#!/usr/bin/env ruby
# the above shebang lets the file know it's a ruby file

require_relative 'lib/month'
require_relative 'lib/year'

case ARGV.length
  when 3
    puts 'Provide either a year (1800-3000), or a Month (MM) and a year(1800-3000)'
  when 2
    month = ARGV[0].to_i
    year = ARGV[1].to_i
    month = Month.new(month,year)
    puts month.to_s
  when 1
    year = ARGV[0].to_i
    year = Year.new(year)
    puts year.to_s
  when 0
    puts 'Provide either a year (1800-3000), or a Month (MM) and a year(1800-3000)'
end
